### ISSUE TITLE
find validated verification template

### ISSUE THREAD

**Issue by A-Annan** [Hajan-io/comming-soon#1]
find template like this 

![Image](https://github.com/Hajan-io/comming-soon/assets/23015439/f1f164fd-d847-47f0-af14-bfdea6e2d0e5)

**Comment by A-Annan** [comment]
https://github.com/aoubid/Congratulation-Template @aoubid

**Comment by A-Annan** [comment]
https://github.com/aoubid/Congratulation-Template
https://github.com/funador/react-confirm-email
@Ayoub1445

**Comment by Ayoub1445** [comment]
https://github.com/funador/react-confirm-email
https://github.com/paulkr/overhang.js
https://github.com/imRohan/vue-confirmation-button
